name: Periodic health check

on:
  workflow_dispatch:   # allows manual run
  schedule:
    - cron: '0 0 * * *'   # runs once per day

jobs:
  health_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check deployed app health
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://ci-cd-7kb1.onrender.com/health
          max-attempts: 3
          retry-delay: 5s
          follow-redirect: true