name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Check style
        run: npm run lint

      - name: Check run test
        run: npm run test

      - name: Check run playwright
        run: npm run eslint