name: Exercise workflow

on:
  push:

jobs:
Date/Time:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print date
        run: date

      - name: List directory contents
        run: ls -l